allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
  - 0bsd
  - unlicense

ignored:
  yarn:
    - json-schema

reviewed:
  bundler:
    - activerecord
    - bcrypt
    - concurrent-ruby
    - websocket-driver
    - websocket-extensions
  
  yarn:
    - webpack
    - yargs
    - typedarray
    - tty-browserify
    - \@webassemblyjs/helper-fsm
    - \@webassemblyjs/leb128
    - \@xtuc/ieee754
    - abbrev
    - atob
    - bcrypt-pbkdf
    - block-stream
    - cacache*
    - caniuse-lite
    - case-sensitive-paths-webpack-plugin
    - color-convert
    - dom-serializer
    - domain-browser
    - estraverse*
    - esutils
    - figgy-pudding
    - fs.realpath
    - glob
    - ieee754
    - json-parse-even-better-errors
    - electron-to-chromium
    - lodash
    - lodash._reinterpolate
    - lodash.debounce
    - lodash.get
    - lodash.has
    - lodash.memoize
    - lodash.template
    - lodash.templatesettings
    - lodash.uniq
    - minizlib
    - nan
    - neo-async
    - normalize-package-data
    - pako
    - path-browserify
    - postcss-color-gray
    - postcss-load-config
    - postcss-loader
    - qs
    - readdirp*
    - sax
    - serialize-javascript*
    - sprintf-js
    - ssri*
    - svgo
    - terser*

