version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install sqlite3 libsqlite3-dev
            sudo apt-get install cmake
            sudo gem update --system
            gem install bundler
            bundle check || bundle config set --local path 'vendor/bundle' || bundle install --jobs=6 --retry=3
      - run: 
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: install webpack
          command: |
            sudo apt-get install nodejs
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt update && sudo apt install yarn
            gem install rails
            rails webpacker:install
      - persist_to_workspace:
          root: /root/project
          paths: src/public/

  brakeman:
    docker:
      - image: cimg/ruby:3.0.0
    executor: ruby/default
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: Brakeman
          command: bundle exec brakeman
      
  licensed:
    docker:
      - image: cimg/ruby:3.0.0
    executor: ruby/default
    steps:
      - attach_workspace:
          at: /root/project
      - run: bundle exec licensed cache
      - run: bundle exec licensed status

  fossa:
    docker:
      - image: cimg/ruby:3.0.0
    executor: ruby/default
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run: fossa init
      - run: 
          command: fossa analyze
          working_directory: ~/project

workflows:
  version: 2
  integration:
    jobs:
      - build
      - brakeman:
          requires: 
            - build
      - licensed:
          requires:
            - brakeman
    #  - fossa
    #    requires:
    #      - brakeman
