version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  brakeman:
    docker:
      - image: cimg/ruby:3.0.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install sqlite3 libsqlite3-dev
            sudo apt-get install cmake
            sudo gem update --system
            gem install bundler
            bundle check || bundle config set --local path 'vendor/bundle' || bundle install --jobs=6 --retry=3
      - run: 
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Brakeman
          command: bundle exec brakeman
      
  licensed:
    docker:
      - image: cimg/ruby:3.0.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install sqlite3 libsqlite3-dev
            sudo apt-get install cmake
            sudo gem update --system
            gem install bundler
            bundle check || bundle config set --local path 'vendor/bundle' || bundle install --jobs=6 --retry=3
      - run: 
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run: bundle exec licensed cache
      - run: bundle exec licensed status

workflows:
  version: 2
  brakeman:
    jobs:
      - brakeman:
      - licensed: